version: "3"

services:
  web:
    # replace v-- with your name and image details
    image: olegtsyba/somestuff:p5
    command: ["yarn", "start"]
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis:alpine
    #ports:
    #  - "6379:6379"
    volumes:
      - /home/docker-user/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet


networks:
  webnet:

